### ISSUE TITLE
dvscifar10训练准确率保持10%不变

### ISSUE THREAD

**Issue by 2ephyrus** [langfengQ/MLF-DSResNet#1]
训练页面正常，loss改变但acc保持10%不变，从1-100代运行，均是如此：
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/fcc6d066-99b4-4bd3-93bd-ee8f008bf623)

超参数设置如下（仅改变了批次和迭代次数）：
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/024cfa6a-2321-4ebd-aba1-17ed9319f47c)

另外，preprocess函数可以正常运行，这是数据集放置的路径（红色方框可以生成hdf5文件）：
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/dd0a3a46-2305-4df7-bf38-4b97167211cf)

请问是什么原因导致的准确率不变？如果需要我提供更多的信息，请指出，期待您的回复！

**Comment by 2ephyrus** [comment]
补充一张训练图片
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/cb60682b-2934-4ff7-a673-28e85ab075bf)

**Comment by langfengQ** [comment]
我重新git clone这个仓库，然后设置了你的参数，暂时没有出现从第一个epoch就是10%的情况。
![image](https://github.com/langfengQ/MLF-DSResNet/assets/94028949/c4940089-426f-4cd4-a101-1613fd18a072)

**Comment by 2ephyrus** [comment]
好的，我去重新clone一下试试。另外，想问一下你这个曲线是如何绘制的？

**Comment by 2ephyrus** [comment]
谢谢你，准确率保持不变的问题解决了，错误原因在于我错误引入一个变量。

**Comment by langfengQ** [comment]
👌，但是我用你的小batch size，会增加训练的不稳定性，得到的最终结果在60%多点。建议有条件还是用原始参数。

**Comment by 2ephyrus** [comment]
作者，请问代码训练完成后的绘制曲线数据可以在哪找到？另外，我该如何绘制类似论文中的曲线？我看代码中没有涉及到绘图的部分，是有什么快捷的方法可以得到曲线吗？
