### ISSUE TITLE
dvsgesture预处理函数结果为空

### ISSUE THREAD

**Issue by 2ephyrus** [langfengQ/MLF-DSResNet#2]
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/e0b1ff63-5419-498a-8ba3-a65cfcee060e)

数据集路径如下：
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/a1d3ecc5-a4ee-44cb-b44e-4535ac842f03)

代码我并未作出修改，请问我该如何修改能使得preprocess正常处理得到hdf5文件？

**Comment by 2ephyrus** [comment]
得到空文件夹
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/6738fc31-a6ec-4e64-94a7-31fc0c5be602)

**Comment by langfengQ** [comment]
路径问题
https://github.com/langfengQ/MLF-DSResNet/blob/1e29706974b78126c7a6ea4c28cb24a3416adce0/DVS_Gesture_preprocess.py#L169
改成 `create_hdf5(os.path.join(path, 'source_DvsGesture/DvsGesture'), path) `

不过你DvsGesture.tar.gz文件好像没有正确解压？

**Comment by 2ephyrus** [comment]
我是用bandzip解压这个文件，然后复制到文件夹下，请问这种方法是否可行？

**Comment by 2ephyrus** [comment]
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/c1cde67a-6718-459a-a25b-0cfc629d2598)
两次解压后就得到了文件夹

**Comment by 2ephyrus** [comment]
train_for_gesture.py中这里选中的部分应该删除掉，主函数就可以运行了
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/378b6be1-1c9e-49a8-9dfb-7e15685b377a)

**Comment by langfengQ** [comment]
> train_for_gesture.py中这里选中的部分应该删除掉，主函数就可以运行了 ![image](https://private-user-images.githubusercontent.com/153836145/291922449-378b6be1-1c9e-49a8-9dfb-7e15685b377a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODQ2NjQsIm5iZiI6MTcwMzA4NDM2NCwicGF0aCI6Ii8xNTM4MzYxNDUvMjkxOTIyNDQ5LTM3OGI2YmUxLTFjOWUtNDlhOC05ZGZiLTdlMTU2ODViMzc3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxNDU5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTI3ODY0ZTIzODg4OWM0YTJlNDAyY2RjMDBmZjg2MjM5Mzk1Nzc2NGYyN2NiZjI3ZTBkNGQ4NGVkZTE4OTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FFge3UBangxKJuZUrcGP1ClcADIhwpdwTaCcA1QanCI)

https://github.com/langfengQ/MLF-DSResNet/blob/ebf325ddf61fa3df5581878c5f170972b81920b5/train_for_gesture.py#L15

好像没有这个问题
