### ISSUE TITLE
超参数的设置

### ISSUE THREAD

**Issue by 2ephyrus** [langfengQ/MLF-DSResNet#3]
作者您好，
请问膜时间常数和阈值这些超参数是如何设置初始值的？
另外，您能否提供针对本文来讲，这些超参数的限制区间？以及，这些超参数是否具有继续训练的价值？（您预设的初始值已经逼近最优解了吗？）

**Comment by 2ephyrus** [comment]
![image](https://github.com/langfengQ/MLF-DSResNet/assets/153836145/c8999e0a-9f58-4589-aba4-5fd1120ffb62)

**Comment by langfengQ** [comment]
没有调节过超参数，直接使用的tdBN（Going Deeper With Directly-Trained Larger Spiking Neural Networks）的超参数。除了Vth。

**Comment by 2ephyrus** [comment]
请问Vth的取值有什么范围吗？是否有些取值会导致训练梯度消失或爆炸？

**Comment by langfengQ** [comment]
我们在工作中没有过多探索过Vth的影响，我们在工作中设置过0.5-0.7，感觉性能对此并不敏感，因此设置合理范围应该都可以。

可以参考Direct training for spiking neural networks: Faster, larger, better

**Comment by langfengQ** [comment]
![image](https://github.com/langfengQ/MLF-DSResNet/assets/94028949/edef71a8-8364-40e9-aed8-5b6582d9f97f)

**Comment by 2ephyrus** [comment]
好，谢谢作者
